### ISSUE TITLE
[OTHER] - Add Engines field

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/twitter-webhook#4]
# Other Issue

## Describe the issue

The following property needs to be added to the `package.json`:

```json
  "engines": {
    "node": "^15.10.0",
    "npm": "^7.6.0"
  },
```

**Comment by bishalr0y** [comment]
Hello @nhcarrigan can I work on this issue?

**Comment by nhcarrigan** [comment]
Hey there!

This project has been a bit of a struggle to keep working, and I am likely going to archive it.

If you'd like to submit the PR for the sake of learning and getting some more contributing experience, I'm happy to accept the contribution and work with you before I archive this. If not, let me know. 🙂

**Comment by bishalr0y** [comment]
I want to still contribute to it for learning and getting some contributing experience.
Can I add the properties at the end of the package.json file?

**Comment by nhcarrigan** [comment]
Yep - they can go at the end of the file. :)
